amazonProperties:
  endpointUrl: https://abhinav-mishra-bucket.s3.ap-south-1.amazonaws.com
  accessKey: AKIAR5CBEQIDPQ4UX25X
  secretKey: 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
  bucketName: abhinav-mishra-bucket